services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: embedding_db
      DB_USER: user
      DB_PASSWORD: password

  db:
    image: pgvector/pgvector:pg17  # prebuilt postgres image with pgvector
    restart: always
    environment:
      POSTGRES_DB: embedding_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: